"""Add profile_picture and image_url columns

Revision ID: fcff44f37f42
Revises: 
Create Date: 2024-06-16 00:29:44.419063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcff44f37f42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'buyer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'total_price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('orders', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('products', 'available_quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('products', 'category')
    op.alter_column('reviews', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'comment',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('users', sa.Column('profile_picture', sa.String(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'profile_picture')
    op.alter_column('reviews', 'comment',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reviews', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('products', sa.Column('category', sa.VARCHAR(), nullable=True))
    op.alter_column('products', 'available_quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('orders', 'total_price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('orders', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'buyer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
